### ISSUE TITLE
Удаление менеджеров

### ISSUE THREAD

**Issue by Aidanushka** [DeeDooMan/Sonoon#15]
- [ ] После удаления себя (на правах администратора) из списка менеджеров, пользователя не выбрасывает из его аккаунта. Он может дальше пользоваться сайтом на правах администратора и изменять роли других пользователей. После выхода из профиля, зайти под удаленным аккаунтом невозможно.

**Comment by zhamahz** [comment]
нельзя удалять админа, сайт без него пропадет
